{"name": "Unsuccessful login with invalid credentials", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\lclar\\Documents\\todoist - Selenium\\.venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lclar\\Documents\\todoist - Selenium\\.venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 57, in step_impl\n    assert context.login_page.get_error_message() == error_message\n"}, "steps": [{"name": "Given a web browser is at the todoist login page", "status": "passed", "start": 1722707693798, "stop": 1722707696082}, {"name": "When a user provides incorrect Todoist credentials and clicks on the Todoist login button", "status": "passed", "steps": [{"name": "Entering username: invalidUser1@gmail.com", "status": "passed", "start": 1722707696085, "stop": 1722707698351}, {"name": "Entering password", "status": "passed", "start": 1722707698351, "stop": 1722707698493}, {"name": "Clicking on login button", "status": "passed", "start": 1722707698493, "stop": 1722707698692}, {"name": "Entering username: invalidUser2@gmail.com", "status": "passed", "start": 1722707698692, "stop": 1722707698871}, {"name": "Entering password", "status": "passed", "start": 1722707698871, "stop": 1722707699047}, {"name": "Clicking on login button", "status": "passed", "start": 1722707699047, "stop": 1722707699157}], "attachments": [{"name": ".table", "source": "84a6b7b2-231a-4913-b95a-b1fcf12a03f5-attachment.csv", "type": "text/csv"}], "start": 1722707696082, "stop": 1722707699157}, {"name": "Then the Todoist error message \"Invalid email or password.\" is displayed", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\lclar\\Documents\\todoist - Selenium\\.venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lclar\\Documents\\todoist - Selenium\\.venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 57, in step_impl\n    assert context.login_page.get_error_message() == error_message\n"}, "steps": [{"name": "Checking error message: Invalid email or password.", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"features\\steps\\login_steps.py\", line 57, in step_impl\n    assert context.login_page.get_error_message() == error_message\n"}, "start": 1722707699158, "stop": 1722707699198}], "start": 1722707699158, "stop": 1722707699222}], "start": 1722707693797, "stop": 1722707701308, "uuid": "556e69c8-5ba8-4409-9136-b78ab2347841", "historyId": "ebd0fd2c49b770f03a8a924c9cc97ea2", "fullName": "Todoist Login: Unsuccessful login with invalid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Todoist Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}